
/**************************************************************
 *	
 *	bark, 8 bit, 11025Hz,
 *	1 channel, 42000 bytes/channel
 *	Total Size: 1 * 42000 + 4 (header) = 42044 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Documents and Settings\Hannah\My Documents\Visual Studio 2008\Projects\Final_HannahYu\bark.wav
 *	Time-stamp: Wed Apr 28 00:26:41 2010
 *	
 **************************************************************/

#ifndef __BARKH__
#define __BARKH__

#define BARKFREQ 11025
#define BARKLEN 42000

extern const unsigned char bark[42000];

#endif /* __BARKH__ */
