
/**************************************************************
 *	
 *	bgsound, 8 bit, 44100Hz,
 *	1 channel, 1102500 bytes/channel
 *	Total Size: 1 * 1102500 + 4 (header) = 1102544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Documents and Settings\Hannah\Desktop\bgsound.wav
 *	Time-stamp: Tue Apr 20 23:32:49 2010
 *	
 **************************************************************/

#ifndef __BGSOUNDH__
#define __BGSOUNDH__

#define BGSOUNDFREQ 44100
#define BGSOUNDLEN 1102500

extern const unsigned char bgsound[1102500];

#endif /* __BGSOUNDH__ */
