
/**************************************************************
 *	
 *	footsteps, 8 bit, 48000Hz,
 *	1 channel, 27824 bytes/channel
 *	Total Size: 1 * 27824 + 4 (header) = 27868 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Documents and Settings\Hannah\Desktop\footsteps.wav
 *	Time-stamp: Tue Apr 20 23:56:38 2010
 *	
 **************************************************************/

#ifndef __FOOTSTEPSH__
#define __FOOTSTEPSH__

#define FOOTSTEPSFREQ 48000
#define FOOTSTEPSLEN 27824

extern const unsigned char footsteps[27824];

#endif /* __FOOTSTEPSH__ */
